" VIMRC 
" Btabone 2020-08-04
color onedark 
set ruler
" Show in proces commands
set showcmd
set number numberwidth=3 relativenumber
"
" ******************************************
" Setup handy mappings
"
let mapleader = ","
" Move line up one in normal mode
nnoremap - ddkP
" Select a word in normal mode
nnoremap <leader><space> viw
" Delete a line in insert mode
inoremap <c-d> <esc>ddi
" Uppercase a word in insert mode
inoremap <c-u> <esc>VUi
" Uppercase a word in normal mode
nnoremap <c-u> VU
" Edit vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
" Set file type unix
nnoremap <leader>u :set ff=unix<cr>
" Set file type dos
nnoremap <leader>d :set ff=dos<cr>
" Source vimrc
nnoremap <leader>sv :source $MYVIMRC<cr>
" Double quote word
nnoremap <leader>" viw<esc>a"<esc>hbi"<esc>lel
" Single quote word
nnoremap <leader>' viw<esc>a'<esc>hbi'<esc>lel
" Put register numbered registers
nnoremap <leader>0 "0p
nnoremap <leader>1 "1p
nnoremap <leader>2 "2p
nnoremap <leader>3 "3p
nnoremap <leader>4 "4p
nnoremap <leader>5 "5p
nnoremap <leader>6 "6p
nnoremap <leader>7 "7p
nnoremap <leader>8 "8p
nnoremap <leader>9 "9p
" Display registers
nnoremap <leader>r :reg<cr>
" In Visual mode, surround selected text with double quotes
vnoremap <leader>" <esc>`<i"<esc>`>la"<esc>
" In visual mode, surround selected text with single quotes 
vnoremap <leader>' <esc>`<i'<esc>`>la'<esc>
" Quick escape out of insert mode
inoremap jk <esc>
" Force ourselves to use the jk sequence
inoremap <esc> <nop>
"
" Abbreviations
iabbrev ccopy Copyright 2020 Brian Tabone, all rights reserved
iabbrev @@ brian.tabone@gmail.com

" Useful autocommands
augroup xmlformatter
	au!
	au FileType xml setlocal equalprg=xmllint\ --format\ --recover\ -\ 2>/dev/null
augroup END

augroup makefiles
    autocmd!
    " Adapted from https://superuser.com/questions/632657/how-to-setup-vim-to-edit-both-makefile-and-normal-code-files
    " in makefiles, don't expand tabs to spaces, since actual tab characters are
    " needed, and have indentation at 8 chars to be sure that all indents are tabs
    " (despite the mappings later):
    autocmd FileType make set noexpandtab shiftwidth=8 softtabstop=0
augroup END
